;; venmos .emacs.d/elisp/init.el
;; http://blog.venmos.com
;; me[at]venmos.com

;; my
(setq user-full-name "venmos")
(setq user-mail-address "venmos@fuck.gfw.es")
(add-to-list 'load-path "~/.emacs.d/my-elisp/")
;; default
(require 'init-elpa)
(require 'init-switch-meta)
(require 'init-emacs)
(require 'init-ibuffer)
(require 'init-ido)
(require 'init-fiplr)
(require 'init-dired)
;;; ui
(require 'init-start-messenge)
(require 'init-tabbar)
(require 'powerline)
(require 'theming)
(require 'init-color-theme)
(require 'init-chinese-fonts)
;(require 'init-diminish)
(require 'init-pangu-spacing)
(require 'init-whitespace-cleanup)
(require 'unicad)
;;; gpg
(require' init-easypg)
(require 'init-gnupg-epa)
;;; shell
(require 'init-shell)
(require 'init-eshell)
;; edit
(require 'init-kill-ring-ido)
(require 'init-ace-jump-mode)
(require 'init-outline)
(require 'init-yasnippet)
(require 'init-multiple-cursors)
(require 'init-company)
(require 'init-expand-region)
;; search
(require 'init-helm-cmd-t)
(require 'init-ag)
(require 'init-pinyin-search)
;(require 'ido-pinyin)
;; file
(require 'init-file)
(require 'init-org-mode)
(require 'init-simplenote)
;;; network
(require 'init-w3m)
(require 'init-eww)
(require 'init-network)
(require 'init-twittering-mode)
(require 'init-google-translate)
(require 'init-erc)
(require 'init-elfeed)
(require 'init-one)
(require 'init-weibo)
(require 'init-osx-browse)
;; tools
(require 'init-dash)
(require 'init-keyfreq)
(require 'init-emacs-chrome)
(require 'init-vagrant)
(require 'init-dayone)
(require 'init-magit)
(require 'init-org-page)

;; disable init ../old-init

;(require 'init-mew)
;(require 'init-el-get)
;(require 'ssl)
;(require 'init-proxy)
;(require 'init-show-point)
;(require 'init-autopair)
;(require 'init-flycheck)
;(require 'init-flycheck-color)
;(require 'init-indent-region) 
;(require 'init-highlight-parentheses)
;(require 'init-indent-hints)
;(require 'init-mu4e)
;(require 'init-weibo)
;(require 'init-dired-single)
;(require 'init-dired-isearch)
;(require 'init-dired-tar)
;(require 'init-eim)
;(require 'init-ruby-mode)
;(require 'init-markdown-mode)
;(require 'init-nxml-mode)
;(require 'init-web-mode)
;(require 'init-emacs-swoop)
;(require 'init-prodigy)
;(require 'init-octopress-emacs)
;(require 'init-guide-key)
;(require 'init-undo-tree)
;(require 'init-helm)
;(require 'init-color-dired)
;(require 'init-mode-line)
 ;(require 'init-newsticker)
;(require 'main-line)
;(setq main-line-separator-style 'wave)
;(defmain-line row "%4l")
;(require 'init-smart-mode)
;;; init.el ends here

